export { createSlotRenderer } from './createRenderer.js'
export type {
  FrameLayout,
  PaylineStyle,
  RendererEvent,
  RendererFit,
  RendererOptions,
  SfxKey,
  ShowWinsOptions,
  SlotRenderer,
  SpinHandle,
  SpinToOptions,
  Theme,
  ThemePalette,
} from './types.js'
export {
  loadTheme,
  parseTheme,
  resolveAssetUrl,
  resolveFrameWindow,
  resolveSymbolSource,
  themeFileUrl,
  FrameLayoutSchema,
  FrameWindowSchema,
  FxEffectSchema,
  FxMapSchema,
  SheetMapSchema,
  SheetSymbolSchema,
  FxSymbolSchema,
  FX_TYPES,
  ThemeError,
  ThemeFileSchema,
  ThemePaletteSchema,
  SfxSchema,
  SFX_KEYS,
  type LoadThemeOptions,
  type ParseThemeOptions,
  type SymbolSource,
  type FxEffect,
  type FxMap,
  type FxSymbol,
  type SheetMap,
  type SheetSymbol,
  type SymbolSourceKind,
  type ThemeFile,
} from './theme.js'
export {
  dedupePositions,
  normalizePosition,
  reelStripWindow,
  spinTargetPosition,
  stopsToGrid,
  symbolAt,
  symbolAtPosition,
  symbolsAtPositions,
  wrapIndex,
} from './grid.js'
export {
  cellPitch,
  computeFrameLayout,
  computeLayout,
  computeWindowFitLayout,
  frameWindowRect,
  paylinePoints,
  positionRects,
  reelLeft,
  rowTop,
  symbolCenter,
  type FramedLayout,
  type FramedLayoutInput,
  type FrameWindow,
  type Layout,
  type LayoutInput,
  type Point,
  type Rect,
  type WindowFitInput,
  type WindowFitLayout,
} from './layout.js'
export {
  buildSkipPlan,
  buildSpinPlan,
  type ReelSpinPlan,
  type SkipPlan,
  type SpinPlan,
  type SpinPlanInput,
} from './timing.js'
export { buildPulsePath, pulsePointAt, type PulsePath, type PulseWaypoint } from './pulse.js'
export { isChromaGreen, keyOutGreen } from './chromaKey.js'
export {
  atlasUrlFor,
  isSheetOnly,
  parseSpriteSheet,
  planSheetFx,
  sheetAnimationSpeed,
  sheetDurationMs,
  sheetFrameIndexAt,
  sheetFrameMs,
  sheetScaleFor,
  SheetError,
  SheetFrameSchema,
  SpriteSheetSchema,
  type SheetFrame,
  type SheetFxPlan,
  type SpriteSheet,
} from './sheet.js'
export {
  planSparkles,
  type RandomFn,
  type SparklePlacement,
  type SparklePlanOptions,
} from './ambient.js'
export {
  buildModeTransition,
  isFreeSpinsActive,
  modeTransitionTarget,
  type ModeTarget,
  type TransitionOptions,
  type TransitionPlan,
} from './transition.js'
export {
  findFreeSpins,
  formatFreeSpinsPlaque,
  isFreeSpinsTrigger,
  isScatterWinTrigger,
  scatterPositions,
  shouldShowFreeSpinsPlaque,
  type FeatureTrigger,
  type FreeSpinsMode,
  type FreeSpinsTrigger,
  type RendererMode,
  type ScatterWinTrigger,
} from './features.js'
export {
  buildPresentation,
  defaultLineLabel,
  phaseAllDurationMs,
  presentationCycleMs,
  type PresentationOptions,
  type PresentationStep,
} from './presentation.js'
export {
  fxAmplitude,
  fxPulseScale,
  fxSegmentDelayMs,
  fxStaggerDelayMs,
  resolveFxEffect,
  resolveFxForPositions,
  resolveSymbolFx,
  BUILTIN_FX,
  FX_DEFAULT_KEY,
  type FxType,
  type PositionFx,
  type ResolvedFxEffect,
} from './fx.js'
export {
  buildWinCycle,
  formatWinLabel,
  isBigWin,
  paylineColor,
  totalWinOf,
  winBetMultiple,
  winTier,
  WIN_TIERS,
  type WinCycleStep,
  type WinTier,
} from './wins.js'
export {
  applyMutationEventsToGrid,
  buildMutationPlan,
  mutationCellDelayMs,
  mutationCommitMs,
  mutationDurationMs,
  mutationReels,
  type MutationKind,
  type MutationPlan,
  type MutationPlanOptions,
  type MutationStep,
} from './mutations.js'
export {
  betUnitCount,
  defaultWaysLabel,
  isBothWays,
  isWaysGame,
  isWaysWin,
  sortWaysWins,
  waysCountOf,
  waysDirectionOf,
  type WaysDirection,
} from './ways.js'
export { resolveReducedMotion, resolveResolution } from './motion.js'
export * from './constants.js'
