export { createSlotRenderer } from './createRenderer.js'
export type {
  FrameLayout,
  RendererEvent,
  RendererFit,
  RendererOptions,
  SfxKey,
  ShowWinsOptions,
  SlotRenderer,
  SpinToOptions,
  Theme,
  ThemePalette,
} from './types.js'
export {
  loadTheme,
  parseTheme,
  resolveAssetUrl,
  resolveFrameWindow,
  resolveSymbolSource,
  themeFileUrl,
  FrameLayoutSchema,
  FrameWindowSchema,
  FxEffectSchema,
  FxMapSchema,
  FxSymbolSchema,
  FX_TYPES,
  ThemeError,
  ThemeFileSchema,
  ThemePaletteSchema,
  SfxSchema,
  SFX_KEYS,
  type LoadThemeOptions,
  type ParseThemeOptions,
  type SymbolSource,
  type FxEffect,
  type FxMap,
  type FxSymbol,
  type SymbolSourceKind,
  type ThemeFile,
} from './theme.js'
export {
  normalizePosition,
  reelStripWindow,
  spinTargetPosition,
  stopsToGrid,
  symbolAt,
  symbolAtPosition,
  symbolsAtPositions,
  wrapIndex,
} from './grid.js'
export {
  cellPitch,
  computeFrameLayout,
  computeLayout,
  computeWindowFitLayout,
  frameWindowRect,
  paylinePoints,
  positionRects,
  reelLeft,
  rowTop,
  symbolCenter,
  type FramedLayout,
  type FramedLayoutInput,
  type FrameWindow,
  type Layout,
  type LayoutInput,
  type Point,
  type Rect,
  type WindowFitInput,
  type WindowFitLayout,
} from './layout.js'
export { buildSpinPlan, type ReelSpinPlan, type SpinPlan, type SpinPlanInput } from './timing.js'
export { isChromaGreen, keyOutGreen } from './chromaKey.js'
export {
  planSparkles,
  type RandomFn,
  type SparklePlacement,
  type SparklePlanOptions,
} from './ambient.js'
export {
  findFreeSpins,
  formatFreeSpinsPlaque,
  isFreeSpinsTrigger,
  isScatterWinTrigger,
  scatterPositions,
  shouldShowFreeSpinsPlaque,
  type FeatureTrigger,
  type FreeSpinsMode,
  type FreeSpinsTrigger,
  type RendererMode,
  type ScatterWinTrigger,
} from './features.js'
export {
  buildPresentation,
  defaultLineLabel,
  phaseAllDurationMs,
  presentationCycleMs,
  type PresentationOptions,
  type PresentationStep,
} from './presentation.js'
export {
  fxAmplitude,
  fxPulseScale,
  fxSegmentDelayMs,
  fxStaggerDelayMs,
  resolveFxEffect,
  resolveFxForPositions,
  resolveSymbolFx,
  BUILTIN_FX,
  FX_DEFAULT_KEY,
  type FxType,
  type PositionFx,
  type ResolvedFxEffect,
} from './fx.js'
export {
  buildWinCycle,
  formatWinLabel,
  isBigWin,
  paylineColor,
  totalWinOf,
  winBetMultiple,
  winTier,
  WIN_TIERS,
  type WinCycleStep,
  type WinTier,
} from './wins.js'
export { resolveReducedMotion, resolveResolution } from './motion.js'
export * from './constants.js'
